export const colors = [
  { id: "0", name: "army", label: "Army", value: "#aebf18" },
  { id: "1", name: "blue", label: "Blue", value: "#3f7efd" },
  { id: "2", name: "brown", label: "Brown", value: "#b1632f" },
  { id: "3", name: "cyan", label: "Cyan", value: "#06c9d0" },
  { id: "4", name: "gold", label: "Gold", value: "#d5ad3f" },
  { id: "5", name: "green", label: "Green", value: "#16b264" },
  { id: "6", name: "grey", label: "Grey", value: "#737373" },
  { id: "7", name: "lavender", label: "Lavender", value: "#c070cd" },
  { id: "8", name: "magenta", label: "Magenta", value: "#b3326f" },
  { id: "9", name: "navy", label: "Navy", value: "#3843a8" },
  { id: "10", name: "orange", label: "Orange", value: "#ef6820" },
  { id: "11", name: "purple", label: "Purple", value: "#7a5af7" },
  { id: "12", name: "red", label: "Red", value: "#c6342f" },
  { id: "13", name: "turquoise", label: "Turquoise", value: "#3e9797" },
  { id: "14", name: "yellow", label: "Yellow", value: "#eaaa08" },
]

export const categories = [
  { id: "0", name: "bills", label: "Bills" },
  { id: "1", name: "education", label: "Education" },
  { id: "2", name: "entertainment", label: "Entertainment" },
  { id: "3", name: "food-drink", label: "Food & Drinks" },
  { id: "4", name: "general", label: "General" },
  { id: "5", name: "groceries", label: "Groceries" },
  { id: "6", name: "health", label: "Health" },
  { id: "7", name: "personal-care", label: "Personal Care" },
  { id: "8", name: "salary", label: "Salary" },
  { id: "9", name: "shopping", label: "Shopping" },
  { id: "10", name: "transportation", label: "Transportation" },
  { id: "11", name: "travel", label: "Travel" },
]
