name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HUSKY: 0

jobs:
  e2e-tests:
    name: E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
          node-version: 22.16

    - name: Install dependencies
      run: npm ci

    - name: Start Supabase
      run: npx supabase start -x studio,edge-runtime

    - name: Set DATABASE_URL
      run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:54322/postgres" >> $GITHUB_ENV

    - name: Run Prisma migrations
      run: npx prisma migrate deploy

    - name: Generate Prisma client
      run: npx prisma generate
    
    - name: Build app
      run: npm run build

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
